/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface ProjectImages {
  blurhash: string;
  created_at: Generated<number>;
  crop_x: number | null;
  height: number;
  id: string;
  is_active: Generated<number>;
  page_name: string | null;
  page_sequence: number;
  project_id: string;
  side: string | null;
  source_id: string | null;
  storage_key: string;
  transcription: string | null;
  updated_at: Generated<number>;
  width: number;
}

export interface ProjectImageSources {
  blurhash: string;
  created_at: Generated<number>;
  height: number;
  id: string | null;
  page_count: Generated<number>;
  project_id: string;
  storage_key: string;
  width: number;
}

export interface Projects {
  created_at: Generated<string | null>;
  id: string;
  is_handwritten: Generated<number>;
  latitude: number;
  locale: string;
  longitude: number;
  sources: Generated<string>;
  title: string;
  type: string;
  user_id: string | null;
  year_end: number;
  year_start: number;
}

export interface Users {
  email: string;
  google_id: string | null;
  id: string;
  is_admin: Generated<number>;
  token_version: Generated<number>;
}

export interface DB {
  project_image_sources: ProjectImageSources;
  project_images: ProjectImages;
  projects: Projects;
  users: Users;
}
