name: Daily Telegram Records Digest
on:
  schedule:
    - cron: '0 18 * * *' # Запуск о 18:00 UTC (20:00/21:00 за Києвом)
  workflow_dispatch: # Дозволяє запустити Action вручну з інтерфейсу GitHub

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # Only current branch
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Find new records in the last 24 hours
        id: find-files
        run: |
          # Шукаємо додані файли за останні 24 години
          START_COMMIT=$(git rev-list -1 --before="24 hours ago" HEAD)
          if [ -z "$START_COMMIT" ]; then
            START_COMMIT=$(git rev-list --max-parents=0 HEAD | tail -n 1)
          fi
          git diff --name-only --diff-filter=A "$START_COMMIT" HEAD | grep -E '^data/records/.*\.(yaml|yml)$' > added_files.txt || true

          # Вивести знайдені файли також в консоль
            echo "added_files.txt:"
            cat added_files.txt
          if [ -s added_files.txt ]; then
            echo "has_files=true" >> $GITHUB_OUTPUT
          else
            echo "has_files=false" >> $GITHUB_OUTPUT
            echo "Нових файлів за добу не знайдено."
          fi

      - name: Setup Node.js
        if: steps.find-files.outputs.has_files == 'true'
        uses: actions/setup-node@v6
        with:
          cache: 'yarn'
          cache-dependency-path: src/daily-report/yarn.lock
          node-version-file: src/daily-report/.nvmrc

      - name: Install dependencies
        if: steps.find-files.outputs.has_files == 'true'
        run: yarn --frozen-lockfile --prefer-offline
        working-directory: src/daily-report

      - name: Run notification script
        working-directory: src/daily-report
        if: steps.find-files.outputs.has_files == 'true'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: yarn dev
