concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

name: Data Ingestion
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'
      - 'public/csv/**'
      - 'src/populate-typesense/**'
  workflow_dispatch:
    inputs:
      full_sync:
        description: 'Perform a full upsert'
        required: true
        type: boolean
        default: false

jobs:
  populate-typesense:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to accurately compute diffs

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Get changed CSV files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          fail_on_initial_diff_error: true
          files: |
            data/**/*.yaml
            public/csv/**/*.csv
          separator: ','

      - name: Populate Typesense
        run: yarn typesense:populate
        env:
          ADDED_MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
          FULL_SYNC: ${{ inputs.full_sync }}
          NEXT_PUBLIC_TYPESENSE_HOST: ${{ vars.TYPESENSE_HOST }}
          TYPESENSE_ADMIN_KEY: ${{ secrets.TYPESENSE_ADMIN_KEY }}
